routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::post('/webhooks/inbound', 'WhatsappController@incoming');

Route::get('/', function () {
    return view('login');
})->name('home');
Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('mlogin', 'Auth\LoginController@login')->name('mlogin');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['prefix' => 'messages'], function () {
    Route::get('/', ['as' => 'messages', 'uses' => 'MessagesController@index']);
    Route::get('create', ['as' => 'messages.create', 'uses' => 'MessagesController@create']);
    Route::get('create/{client_id}/{process_id}/{step_id}', ['as' => 'messages.client', 'uses' => 'MessagesController@client_create']);
    Route::get('create/{client_id}/{related_party_id}', ['as' => 'messages.relatedparty', 'uses' => 'MessagesController@relatedparty_create']);
    Route::post('/', ['as' => 'messages.store', 'uses' => 'MessagesController@store']);
    Route::get('{id}', ['as' => 'messages.show', 'uses' => 'MessagesController@show']);
    Route::put('{id}', ['as' => 'messages.update', 'uses' => 'MessagesController@update']);
});

Route::get('powerpoint', 'ReportController@powerpoint')->name('powerpoint');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('profile/{user?}', 'UserController@profile')->name('profile');
Route::get('settings', 'UserController@settings')->name('settings');
Route::post('settings/password', 'UserController@handlePassword')->name('settings.password');
Route::post('settings/profile', 'UserController@handleProfile')->name('settings.profile');
Route::post('settings/notifications', 'UserController@handleNotifications')->name('settings.notifications');

Route::any('/', 'HomeController@index')->name('home');
Route::any('/home', 'HomeController@index');
Route::get('recents', 'HomeController@recents')->name('recents');
Route::any('dashboard', 'HomeController@dashboard')->name('dashboard');
Route::any('progress', 'HomeController@progress')->name('progress');
Route::get('calendar', 'HomeController@calendar')->name('calendar');
Route::get('help', 'HelpController@create')->name('help.create');
Route::post('help', 'HelpController@store')->name('help.store');

Route::resource('emaillogs', 'EmailLogsController');
Route::get('emaillogs/{email_id}', 'EmailLogsController@show')->name('emaillogs.show');

/*Route::get('storage/crf', 'AssetController@getCrf')->name('crf_client');*/
Route::get('storage/avatar', 'AssetController@getAvatar')->name('avatar');
Route::get('storage/document', 'AssetController@getDocument')->name('document');
Route::get('storage/template', 'AssetController@getTemplate')->name('template');

Route::get('clients/amlreviewed', 'ClientController@amlReviewed')->name('clients.amlreviewed');
Route::get('clients/amlapproved', 'ClientController@amlApproved')->name('clients.amlapproved');
Route::get('clients/amlreviewedandapproved', 'ClientController@amlReviewedAndApproved')->name('clients.amlreviewedandapproved');
Route::get('clients/completed/{step_id}', 'ClientController@completed')->name('clients.completed');

Route::get('clients/xlsexport','ClientController@xlsExport')->name('clients.xlsexport');
Route::resource('clients', 'ClientController');

Route::any('clients/create','ClientController@create')->name('clients.create');
Route::any('clients/{client}/members/{process}/{step}','ClientController@members')->name('clients.members');
Route::post('clients/{client}/updates','ClientController@update')->name('clients.savedetail');
Route::get('clients/{client}/avatar','ClientController@generateAvatar')->name('clients.avatar');
Route::get('clients/{client}/progress','ClientController@progress')->name('clients.progress');
Route::get('clients/{client}/processes/{process}/{step}/{is_form}','ClientController@processes')->name('clients.processes');
Route::post('clients/{client}/progress','ClientController@storeProgress')->name('clients.storeprogress');
Route::post('clients/{client}/actions','ClientController@storeActions')->name('clients.storeactions');
Route::post('clients/{client}/progress/{process?}/{step?}','ClientController@completeStep')->name('clients.completestep');
Route::post('clients/{client}/progress2/{process?}/{step?}','ClientController@completeStep2')->name('clients.completestep2');
Route::get('clients/{client}/progress/{process}/{step}/{is_form}','ClientController@stepProgress')->name('clients.stepprogress');
Route::get('clients/{client}/progressaction/{process}/{step}/{action_id}','ClientController@stepProgressAction')->name('clients.stepprogressaction');
Route::get('clients/{client}/documents/{process}/{step}/{is_form}','ClientController@documents')->name('clients.documents');
Route::get('clients/{client}/forms/{process}/{step}','ClientController@forms')->name('clients.forms');
Route::get('clients/{client}/edit/{process}/{step}/{is_form}','ClientController@edit')->name('clients.edit');
Route::get('clients/{client}/forms/uploadform','ClientController@uploadforms')->name('forms.uploadforms');
Route::get('clients/{client}/forms/editform/{formid}','ClientController@edituploadforms')->name('forms.editforms');
Route::post('clients/{client}/forms/storeform','ClientController@storeuploadforms')->name('forms.uploadstore');
Route::post('clients/{clientid}/forms/{formid}/formupdate','ClientController@updateuploadforms')->name('forms.formupdate');
Route::get('clients/{client}/forms/createcrf','ClientController@createCrfForm')->name('forms.createcrf');
Route::get('clients/{client}/forms/editcrf/{formid}','ClientController@editCrfForm')->name('forms.editcrf');
Route::get('clients/{client}/forms/signcrf/{formid}','ClientController@signCrfForm')->name('forms.signcrf');
Route::post('clients/{clientid}/forms/{formid}/updatecrf','ClientController@updateCrfForm')->name('forms.updatecrf');
Route::post('clients/{client}/forms/storecrf','ClientController@saveCrfForm')->name('forms.storecrf');
Route::get('clients/{client}/forms/{formid}/generatecrf','ClientController@generateCrfForm')->name('forms.generatecrf');
Route::get('clients/{client}/forms/upload','ClientController@saveCrfForm')->name('forms.upload');
Route::get('clients/{client}/forms/delete/{formid}','ClientController@deleteCrfForm')->name('crfforms.destroy');
Route::get('clients/{client_id}/completed/{step_id}/{newdate}','ClientController@complete')->name('clients.complete');
Route::get('clients/{client_id}/uncompleted/{step_id}','ClientController@uncomplete')->name('clients.uncomplete');
Route::get('clients/{client_id}/changecompleted/{step_id}/{newdate}','ClientController@changecomplete')->name('clients.changecomplete');
Route::post('clients/{client}/sendnotification/{activity?}','ClientController@sendNotification')->name('clients.sendnotification');
Route::post('clients/{client}/sendtemplate/{activity?}','ClientController@sendTemplate')->name('clients.sendtemplate');
Route::post('clients/{client}/senddocument/{activity?}','ClientController@sendDocument')->name('clients.senddocument');
Route::get('clients/{client}/viewtemplate/{template?}','ClientController@viewTemplate')->name('clients.viewtemplate');
Route::get('clients/{client}/viewdocument/{document?}','ClientController@viewDocument')->name('clients.viewdocument');
/*Route::put('clients/{client}/follow','ClientController@follow')->name('clients.follow');*/
Route::get('clients/{client}/activityprogress/{process}/{step}','ClientController@activityProgress')->name('clients.activityprogress');
Route::get('clients/{client}/getcomments','ClientController@getComment')->name('clients.getcomment');
Route::post('clients/{client}/storecomment','ClientController@storeComment')->name('clients.storecomment');
Route::post('clients/deleteclientcomment/{comment}','ClientController@deleteComment')->name('clients.deletecomment');
Route::post('clients/{client}/progressing','ClientController@storeProgressing')->name('clients.progressing');
/*Route::post('clients/{client}/qa','ClientController@storeQA')->name('clients.qa');*/
/*Route::post('clients/{client}/qacomplete','ClientController@completeQA')->name('clients.qacomplete');
Route::post('clients/{client}/qaprod','ClientController@storeProd')->name('clients.qaprod');*/
Route::post('clients/{client}/approval','ClientController@approval')->name('clients.approval');
Route::post('clients/{client}/senddocuments/{activity?}','ClientController@sendDocuments')->name('clients.senddocuments');

Route::post('clients/{client}/sendmail','ClientController@sendMail')->name('clients.sendMail');
Route::post('clients/{client}/sendwhatsapp','ClientController@sendWhatsapp')->name('clients.sendWhatsapp');

Route::post('voice/record/{card}','TaskController@recordVoice')->name('tasks.voicerecord');

Route::get('clients/{clientid}/overview/{process}/{step}','ClientController@overview')->name('clients.overview');
Route::get('clients/{clientid}/details/{process}/{step}/{is_form}','ClientController@details')->name('clients.details');

app/ClientForm.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class ClientForm extends Model
{
    protected $table = 'client_forms';
    protected $touches = ['client'];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function type()
    {
        return pathinfo($this->file, PATHINFO_EXTENSION);
    }

    public function size()
    {
        try {
            $bytes = Storage::size('crf/' . $this->file);
            $i = floor(log($bytes, 1024));
            return round($bytes / pow(1024, $i), [0, 0, 2, 2, 3][$i]) . ['B', 'kB', 'MB', 'GB', 'TB'][$i];
        } catch (\Exception $e) {
            return "LStat";
        }
    }

    public function client()
    {
        return $this->belongsTo('App\Client','client_id');
    }
}

app/ClientHelper.php
<?php


namespace App;


class ClientHelper
{
    public function clientBucketActivityIds($steps, $client, $process_id)
    {
        $tmp_act = $steps->where('process_id', $process_id)->map(function ($step) {
            return $step->activities->map(function ($activ) {
                if ($activ->client_bucket) {
                    return $activ->id;
                }
            });
        })->flatten()->toArray();

        $tmp_act = array_values(array_filter($tmp_act));

        $parent_activities_in_client_basket = ActivityInClientBasket::has('activity')
            ->where('client_id', $client->id)
            ->select('activity_id', 'in_client_basket')
            ->get();

        $flag = $parent_activities_in_client_basket->map(function ($activity_id) {
            return $activity_id->activity_id;
        })->toArray();

        foreach ($tmp_act as $key => $item) {
            if (in_array($item, $flag)) {
                unset($tmp_act[$key]);
            }
        }

        $active_activities = $parent_activities_in_client_basket->where('in_client_basket', 1)->map(function ($activity) {
            return $activity->activity_id;
        })->values()->toArray();

        return array_merge($tmp_act, $active_activities);
    }

    public function clientBucketDetailIds($sections, $client)
    {

        $tmp_act = $sections->map(function ($step) {
            return $step->form_section_inputs->map(function ($activ) {
                if ($activ->client_bucket) {
                    return $activ->id;
                }
            });
        })->flatten()->toArray();

        $tmp_act = array_values(array_filter($tmp_act));

        $parent_activities_in_client_basket = FormSectionInputInClientBasket::where('client_id', $client->id)->select('input_id', 'in_client_basket')
            ->get();

        $flag = $parent_activities_in_client_basket->map(function ($activity_id) {
            return $activity_id->input_id;
        })->toArray();

        foreach ($tmp_act as $key => $item) {
            if (in_array($item, $flag)) {
                unset($tmp_act[$key]);
            }
        }

        $active_activities = $parent_activities_in_client_basket->where('in_client_basket', 1)->map(function ($activity) {
            return $activity->input_id;
        })->values()->toArray();

        return array_merge($tmp_act, $active_activities);
    }

    public function detailedClientBasket($client, $cc = false)
    {
        $form = Forms::find($client->crm_id);
        if (!$form) {
            return null;
        }

        if ($form) {
            $forms = $form->getClientDetailsInputValues($client->id, $form->id);
            $sections = $tmp = FormSection::with('form_section_inputs')->where('form_id', $client->crm_id)->get();

            $cd = $this->clientBucketDetailIds($sections, $client);
            if ($cc) {
                return [
                    'forms' => $forms,
                    'cd' => $cd,
                    'çount' => $sections->map(function ($step) use ($cd) {
                        return [
                            'inputs' => $step->form_section_inputs->filter(function ($activ) use ($cd) {
                                return in_array($activ->id, array_unique($cd));
                            })->values(),
                            'heading' => $step->name
                        ];
                    })
                ];
            }
            return $sections->map(function ($step) use ($cd) {
                return [
                    'inputs' => $step->form_section_inputs->filter(function ($activ) use ($cd) {
                        return in_array($activ->id, array_unique($cd));
                    })->values(),
                    'heading' => $step->name
                ];
            });
        }
    }

    public function clientDetails($client, $cc = false)
    {
        $form = Forms::find($client->crm_id);
        if (!$form) {
            return null;
        }

        if ($form) {
            $forms = $form->getClientDetails($client->id, $form->id);
            $sections = $tmp = FormSection::with('form_section_inputs')->where('form_id', $client->crm_id)->get();

            $cd = $this->clientBucketDetailIds($sections, $client);
            if ($cc) {
                return [
                    'forms' => $forms,
                    'cd' => $cd
                ];
            }
            return $sections->map(function ($step) use ($cd) {
                return [
                    'inputs' => $step->form_section_inputs->filter(function ($activ) use ($cd) {
                        return in_array($activ->id, array_unique($cd));
                    })->values(),
                    'heading' => $step->name
                ];
            });
        }
    }

    public function steps_data($client, $process)
    {
        $client_process = ClientProcess::where('client_id', $client->id)->where('process_id', $process->id)->first();
        $steps = Step::where('process_id', $process->id)->orderBy('order', 'asc')->get();
        $c_step_order = Step::where('id', $client_process->step_id)->withTrashed()->first();
        $step_data = [];
        foreach ($steps as $a_step):
            if ($a_step->deleted_at == null) {
                $progress_color = $process->getStageHex(0);
                $step_stage = 0;

                if ($c_step_order->order == $a_step->order) {
                    $progress_color = $process->getStageHex(1);
                    $step_stage = 1;
                }

                if ($c_step_order->order > $a_step->order) {
                    $progress_color = $process->getStageHex(2);
                    $step_stage = 2;
                }


                $tmp_step = [
                    'id' => $a_step->id,
                    'name' => $a_step->name,
                    'progress_color' => $progress_color,
                    'process_id' => $a_step->process_id,
                    'order' => $a_step->order,
                    'stage' => $step_stage
                ];

                array_push($step_data, $tmp_step);
            }
        endforeach;

        return $step_data;
    }

    public function getClientBasketActivities($client, $process)
    {
        $steps = Step::where('process_id', $process->id)->orderBy('order','asc')->get();

        $activities_in_client_basket = $this->clientBucketActivityIds($steps, $client, $process->id);

        return $steps->map(function ($step) use ($activities_in_client_basket){
            return [
                'activity' => $step->activities->filter(function ($activ) use ($activities_in_client_basket){
                    return in_array($activ->id, array_unique($activities_in_client_basket));
                })->values(),
                'heading' => $step->name,
            ];
        });
    }
}

resources/views/clients/activityprogress.blade.php
@extends('clients.show')

@section('tab-content')
    <div class="col">
        <div class="process_step" id="activity_progress_{{$step->id}}">
            {{--<h3 id="{{$step->id}}" class="p-2" style="background-color: {{$client->process->getStageHex($step->name)}};width:100%;">{{$step->name}}</h3>--}}
            <h3 id="{{$step->id}}" class="p-2" style="width:100%;">{{$step->name}}</h3>
            <div style="padding: 0.5rem"><strong>Completed activities:</strong>
            <ul>
                {!! $completed !!}
            </ul>
                <strong>Not completed activities:</strong>
            <ul>
                {!! $not_completed !!}
            </ul>
            <a href="{{route('clients.progress', $client->id)}}/{{$step->process_id}}/{{$step->id}}">Back to form</a></div>
        </div>
    </div>
@endsection
@section('extra-js')
    {{--<script>
        showActivityProgress({{$id}});
        
        function showActivityProgress(id){
            $("#activity_progress_"+id).show();
        }
    </script>--}}
@endsection

resources/views/clients/amlreports.blade.php
@extends('layouts.app')

@section('title') Clients @endsection

@section('header')
    <h1><i class="fa fa-address-card-o"></i> @yield('title')</h1>
    <a href="{{route('clients.create')}}" class="btn btn-outline-light float-right"><i class="fa fa-plus"></i> Client</a>
@endsection

@section('content')
    <form class="form-inline mt-3">
        Show &nbsp;
        {{Form::select('s',['all'=>'All','mine'=>'My','country'=>'Country wide','region'=>'Region wide','office'=>'Office wide'],old('selection'),['class'=>'form-control form-control-sm'])}}
        &nbsp; for &nbsp;
        {{Form::select('p',$processes ,old('p'),['class'=>'form-control form-control-sm'])}}
        &nbsp; for &nbsp;
        {{Form::select('c',['all'=>'All completions','no'=>'Not completed','yes'=>'Completed'],old('c'),['class'=>'form-control form-control-sm'])}}
        &nbsp; in &nbsp;
        {{Form::select('step',$steps ,old('step'),['class'=>'form-control form-control-sm'])}}
        &nbsp; from &nbsp;
        {{Form::date('f',old('f'),['class'=>'form-control form-control-sm'])}}
        &nbsp; to &nbsp;
        {{Form::date('t',old('t'),['class'=>'form-control form-control-sm'])}}
        &nbsp; matching &nbsp;
        <div class="input-group input-group-sm">
            <div class="input-group-prepend">
                <div class="input-group-text">
                    <i class="fa fa-search"></i>
                </div>
            </div>
            {{Form::text('q',old('query'),['class'=>'form-control form-control-sm','placeholder'=>'Search...'])}}
        </div>
        <button type="submit" class="btn btn-sm btn-secondary ml-2 mr-2"><i class="fa fa-search"></i> Search</button>
        <a href="{{route('clients.index')}}" class="btn btn-sm btn-outline-info"><i class="fa fa-eraser"></i> Clear</a>
    </form>

    <hr>

    <div class="table-responsive">
        <table class="table table-bordered table-sm table-hover">
            <thead class="thead-light">
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Contact</th>
                <th>Process</th>
                <th>Created</th>
                <th>Completed</th>
                <th><abbr title="Days taken to complete a clients process.">Duration</abbr></th>
                <th>Step</th>
                <th>User</th>
            </tr>
            </thead>
            <tbody>
            @forelse($clients as $client)
                <tr>
                    <td><a href="{{route('clients.show',$client)}}">{{$client->company}}</a></td>
                    <td>{{$client->email}}</td>
                    <td>{{$client->contact}}</td>
                    <td>{{$client->process->name}}</td>
                    <td>{{$client->created_at}}</td>
                    <td>{{!is_null($client->completed_at) ? $client->completed_at->toDateString() : ''}}</td>
                    <td>{{$client->completed_days}}</td>
                    <td>{{$client->getCurrentStep()->name}}</td>
                    <td><a href="{{route('profile',$client->introducer)}}" title="{{$client->introducer->name()}}"><img src="{{route('avatar',['q'=>$client->introducer->avatar])}}" class="blackboard-avatar blackboard-avatar-inline" alt="Avatar"/></a></td>
                </tr>
            @empty
                <tr>
                    <td colspan="100%" class="text-center"><small class="text-muted">No clients match those criteria.</small></td></td>
                </tr>
            @endforelse
            </tbody>

        </table>
    </div>

    <small class="text-muted">Found <b>{{sizeof($clients)}}</b> clients matching those criteria.</small>
@endsection

resources/views/clients/index.blade.php
@extends('adminlte.default')

@section('title') Clients @endsection

@section('header')
    <div class="container-fluid container-title">
        <h3>@yield('title')</h3>
        <a href="{{route('clients.create')}}" class="btn btn-dark btn-sm float-right"><i class="fa fa-plus"></i> Client</a>
    </div>
@endsection

@section('content')
    <div class="container-fluid">
    <form class="form-inline mt-3" id="clientform">
        Show &nbsp;
        {{Form::select('s',['all'=>'All','mine'=>'My','country'=>'Country wide','region'=>'Region wide','office'=>'Office wide','deleted'=>'Deleted'],old('selection'),['class'=>'form-control form-control-sm'])}}
        &nbsp; for &nbsp;
        {{Form::select('p',$processes ,old('p'),['class'=>'form-control form-control-sm','id'=>'p'])}}
        &nbsp; for &nbsp;
        {{Form::select('c',['all'=>'All completions','no'=>'Not converted','yes'=>'Converted','progress'=>'Progressing','noprogress'=>'Not progressing','approval'=>'Needs approval'],old('c'),['class'=>'form-control form-control-sm'])}}
        &nbsp; in &nbsp;
        {{Form::select('step',[] ,old('step'),['class'=>'form-control form-control-sm','id'=>'step'])}}
        &nbsp; with &nbsp;
        {{Form::select('rl',$relationship_lead ,old('rl'),['class'=>'form-control form-control-sm','id'=>'rl'])}}
        &nbsp; from &nbsp;
        {{Form::date('f',old('f'),['class'=>'form-control form-control-sm'])}}
        &nbsp; to &nbsp;
        {{Form::date('t',old('t'),['class'=>'form-control form-control-sm'])}}
        &nbsp; matching &nbsp;
        <div class="input-group input-group-sm">
            <div class="input-group-prepend">
                <div class="input-group-text">
                    <i class="fa fa-search"></i>
                </div>
            </div>
            {{Form::text('q',old('query'),['class'=>'form-control form-control-sm','placeholder'=>'Search...'])}}
        </div>
        <button type="submit" class="btn btn-sm btn-secondary ml-2 mr-2"><i class="fa fa-search"></i> Search</button>
        <a href="{{route('clients.index')}}" class="btn btn-sm btn-info"><i class="fa fa-eraser"></i> Clear</a>
    </form>

    <hr>

    <div class="table-responsive">
        <table class="table table-bordered table-hover table-sm">
            <thead class="btn-dark">
            <tr>
                <th>@sortablelink('company', 'Client Name')</th>{{--
                <th>@sortablelink('portfolio_manager', 'Portfolio Manager')</th>
                <th>@sortablelink('project_name', 'Project Name')</th>
                <th>@sortablelink('project_start_date', 'Project Start Date')</th>
                <th>@sortablelink('proposed_end_date', 'ProposedEnd Date')</th>--}}
                {{--<th>@sortablelink('referrer','Referrer')</th>
                <th>@sortablelink('director','Relationship Lead')</th>
                <th>@sortablelink('onboardingl','Onboarding Lead')</th>
                <th>@sortablelink('onboardingm','Onboarding Member In Charge')</th>
                <th>@sortablelink('email', 'Email')</th>
                <th>@sortablelink('contact', 'Contact')</th>--}}
                {{--<th>@sortablelink('process_id', 'Process')</th>--}}
                {{--<th>@sortablelink('created', 'Created')</th>--}}
                @if($np != 0)
                <th>@sortablelink('non_progressing', 'Non Progressing Date')</th>
                @endif
                {{--<th>@sortablelink('converted', 'Converted')</th>
                <th><abbr title="Days taken to complete a clients process.">@sortablelink('duration', 'Duration')</abbr></th>
                <th>@sortablelink('step', 'Step')</th>--}}
                {{--<th><abbr title="Is the client progressing or not."><i class="fa fa-tasks"></i></abbr></th>
                <th><abbr title="Does the client need approval."><i class="fa fa-tasks"></i></abbr></th>--}}
                <th>@sortablelink('introducer', 'User')</th>
            </tr>
            </thead>
            <tbody>
            @forelse($clients['results'] as $client)
                <tr>
                    <td><a href="{{route('clients.show',$client["id"])}}">{{($client["portfolio_name"] != '' ? $client["portfolio_name"] : $client["company"] )}}</a></td>{{--
                    <td>{{$client["portfolio_manager"]}}</td>
                    <td>{{$client["project_name"]}}</td>
                    <td>{{$client["project_start_date"]}}</td>
                    <td>{{$client["proposed_end_date"]}}</td>--}}
                    {{--<td>{{(isset($client["referrer"]) ? $client["referrer"] : '')}}</td>
                    <td>{{(isset($client["director"]) ? $client["director"] : '')}}</td>
                    <td>{{(isset($client["onboardingl"]) ? $client["onboardingl"] : '')}}</td>
                    <td>{{(isset($client["onboardingm"]) ? $client["onboardingm"] : '')}}</td>
                    <td>{{$client["email"]}}</td>
                    <td>{{$client["contact"]}}</td>--}}
                    {{--<td>{{$client["process"]}}</td>--}}
                    {{--<td>{{$client["created_at"]}}</td>--}}
                    @if($np != 0)
                        <td>{{$client["non_progressing"]}}</td>
                    @endif
                    {{--<td>{{!is_null($client["completed_at"]) ? \Carbon\Carbon::parse($client["completed_at"])->format('Y-m-d') : ''}}</td>
                    <td>{{$client["completed_days"]}}</td>
                    <td>{{$client["step"]}}</td>--}}
                    {{--<td>{!!($client["is_progressing"]) ? '' : '<i class="fa fa-exclamation-triangle text-danger"></i>'!!}</td>
                    <td>{!!(!$client["needs_approval"]) ? '' : '<i class="fa fa-asterisk text-danger"></i>'!!}</td>--}}
                    <td><a href="{{route('profile',$client["introducer"])}}"><img src="{{route('avatar',['q'=>$client["avatar"] ])}}" class="blackboard-avatar blackboard-avatar-inline blackboard-avatar-navbar-img" alt="Avatar"/></a></td>
                </tr>
            @empty
                <tr>
                    <td colspan="100%" class="text-center"><small class="text-muted">No clients match those criteria.</small></td></td>
                </tr>
            @endforelse
            </tbody>

        </table>
    </div>


        @include('clients.pagination', ['paginator' => $clients['results'], 'link_limit' => 5])
    </div>
@endsection
@section('extra-js')
    <script>
        /*$('select[name="s"], [name="step"], [name="p"]').change(function () {

            $('#clientform').submit();

        });*/

        $(document).ready(function() {
            if ($('select[name="p"]').val() > 0) {
                $(document).find('#step').empty();
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });

                $.ajax({
                    url: '/reports/getprocesssteps/' + $('select[name="p"]').val(),
                    type: "GET",
                    dataType: "json",
                    success: function (data) {
                        $(document).find('#step').append($("<option></option>").attr("value", '').text('All Steps'));
                        $.each(data, function (key, value) {
                            if(key === '{{ request()->get('step') }}') {
                                $(document).find('#step').append($("<option></option>").attr("value", key).text(value));
                                $('#step').val({{ request()->get('step') }}).attr("selected", "selected");
                            } else {
                                $(document).find('#step').append($("<option></option>").attr("value", key).text(value));
                            }
                        });

                    }
                });
            }

            $('#p').on('change',function()
            {
                if ($('select[name="p"]').val() > 0) {
                    $(document).find('#step').empty();
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });

                    $.ajax({
                        url: '/reports/getprocesssteps/' + $('select[name="p"]').val(),
                        type: "GET",
                        dataType: "json",
                        success: function (data) {
                            $(document).find('#step').append($("<option></option>").attr("value", '').text('All Steps'));
                            $.each(data, function (key, value) {
                                $(document).find('#step').append($("<option></option>").attr("value", key).text(value));
                            });

                        }
                    });
                    $('#step').val({{ request()->get('step') }}).attr("selected", "selected");
                }
            });
        });
    </script>
@endsection